name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    
    - name: Build with Maven
      run: |
        mvn clean package
        
        
    - name: Create custom JRE
      run: |
        # 分析依赖模块
        modules=$(jdeps --ignore-missing-deps --print-module-deps -q target/DeskPet-1.0-SNAPSHOT.jar)
        
        # 创建精简JRE
        jlink --add-modules $modules,java.desktop \
              --strip-debug \
              --no-header-files \
              --no-man-pages \
              --compress=2 \
              --output target/custom-jre
              
     - name: Package DMG
      run: |
        jpackage \
          --name DeskPet \
          --input target \
          --main-jar DeskPet-*.jar \
          --main-class com.hhhu.DesktopPet \
          --runtime-image target/runtime \
          --icon src/main/resources/images/icnsM.icns \
          --type dmg \
          --dest release \
          --app-version "1.0.0" \
          --mac-package-identifier "com.hhhu.DeskPet" \
          --mac-sign \
          --mac-signing-key-user-name "Developer ID"

                 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeskPet-Mac
        path: release/DeskPet-*.dmg