name: Build macOS DMG (Java 21)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-latest

    steps:
      # 1) 签出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) 安装 Temurin 21 JDK（含 jpackage 工具）
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21.0.2'
          cache: 'maven'

      # 3) 用 Maven 打包，跳过测试，生成带依赖的可执行 JAR
      - name: Build JAR with Maven
        run: mvn clean package -DskipTests


      # 5) 安装 create-dmg（用于把 .app 打包成 .dmg）
      - name: Install create-dmg
        run: brew install create-dmg

      # 6) 使用 jpackage 生成 macOS .app
      #    注意：这里假设你的可执行 Jar 在 target/ 目录，名为 DeskPet-1.0-SNAPSHOT-jar-with-dependencies.jar
      - name: Create macOS .app with jpackage
        run: |
          jpackage \
            --name DeskPet \
            --app-version 1.0 \
            --input target \
            --main-jar DeskPet-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --type app-image \
            --icon src/main/resources/images/icnsM.icns\
            --dest output

      # 7) 用 create-dmg 将生成的 .app 打包成 .dmg
      - name: Create DMG from .app
        working-directory: output
        run: |
          create-dmg \
            --volname "DeskPet" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --app-drop-link 460 185 \
            DeskPet.dmg \
            DeskPet.app

      # 8) 上传 .dmg 作为 artifact，便于下载
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: DeskPet-macos-dmg
          path: output/DeskPet.dmg
