name: Build macOS DMG with JDK 21

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    
    - name: Build with Maven
      run: |
        mvn clean package
        
        
    - name: Create modular runtime (JDK 21+)
      run: |
        # JDK 21+ 推荐使用模块化构建
        jdeps --ignore-missing-deps --multi-release 21 --print-module-deps target/DeskPet-*.jar > target/modules.txt
        jlink --add-modules $(cat target/modules.txt),jdk.unsupported \
              --strip-debug \
              --compress=2 \
              --output target/runtime
              
     - name: Package DMG
      run: |
        jpackage \
          --name DeskPet \
          --input target \
          --main-jar DeskPet-*.jar \
          --main-class com.hhhu.DesktopPet \
          --runtime-image target/runtime \
          --icon src/main/resources/images/icnsM.icns \
          --type dmg \
          --dest release \
          --app-version "1.0.0" \
          --mac-package-identifier "com.hhhu.DeskPet" \
          --mac-sign \
          --mac-signing-key-user-name "Developer ID"

                 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeskPet-Mac
        path: release/DeskPet-*.dmg