name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package


    - name: Create DMG package
      run: |
        mkdir -p release
        jpackage \
          --name DeskPet \
          --type dmg \
          --input target \
          --main-jar DeskPet-1.0-SNAPSHOT-jar-with-dependencies.jar \
          --main-class com.hhhu.DesktopPet \
          --icon src/main/resources/images/icons.icns \
          --dest release \
          --verbose



    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeskPet-MacOS
        path: release/*.dmg