name: Build macOS DMG with JDK 21

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Generate ICNS icon
      run: |
        mkdir -p target
        mkdir -p icon.iconset
        
        cp src/main/resources/images/icon.png .
    
        # 生成不同尺寸的图标
        sips -z 16 16 icon.png --out icon.iconset/icon_16x16.png
        sips -z 32 32 icon.png --out icon.iconset/icon_16x16@2x.png
        sips -z 32 32 icon.png --out icon.iconset/icon_32x32.png
        sips -z 64 64 icon.png --out icon.iconset/icon_32x32@2x.png
        sips -z 128 128 icon.png --out icon.iconset/icon_128x128.png
        sips -z 256 256 icon.png --out icon.iconset/icon_128x128@2x.png
        sips -z 256 256 icon.png --out icon.iconset/icon_256x256.png
        sips -z 512 512 icon.png --out icon.iconset/icon_256x256@2x.png
        sips -z 512 512 icon.png --out icon.iconset/icon_512x512.png
        sips -z 1024 1024 icon.png --out icon.iconset/icon_512x512@2x.png
        
        # 转换为 .icns 格式
        iconutil -c icns icon.iconset -o target/deskpet.icns
        
        # 清理临时文件
        rm -rf icon.iconset
        
    - name: Build with Maven
      run: |
        mvn clean package
        
        
    - name: Create modular runtime (JDK 21+)
      run: |
        # JDK 21+ 推荐使用模块化构建
        jdeps --ignore-missing-deps --multi-release 21 --print-module-deps target/DeskPet-*.jar > target/modules.txt
        jlink --add-modules $(cat target/modules.txt),jdk.unsupported \
              --strip-debug \
              --compress=2 \
              --output target/runtime
              
    - name: Package DMG
      run: |
        jpackage --name DeskPet \
                 --input target/ \
                 --main-jar DeskPet-1.0-SNAPSHOT.jar \
                 --main-class com.hhhu.DesktopPet \
                 --runtime-image target/custom-jre \
                 --icon target/deskpet.icns \
                 --type dmg \
                 --dest release \
                 --app-version "1.0.0" \
                 --mac-package-identifier "com.hhhu.DeskPet"
                 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeskPet-Mac
        path: release/DeskPet-*.dmg