name: Build DMG for macOS

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.2'

      - name: Build with Maven
        run: mvn clean package

      - name: Package with jpackage
        run: |
          mkdir -p build/package
          jpackage \
            --type app-image \
            --name DesktopPet \
            --input target \
            --main-jar DeskPet-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class com.hhhu.DesktopPet \
            --icon src/main/resources/images/icon.png \
            --java-options "-Xmx512m" \
            --dest build/package \
            --resource-dir src/main/resources

      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "DesktopPet" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --icon "DesktopPet.app" 175 190 \
            --hide-extension "DesktopPet.app" \
            --app-drop-link 425 190 \
            "DesktopPet.dmg" \
            build/package/DesktopPet.app

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: DesktopPet-DMG
          path: DesktopPet.dmg
